on:
  push:
    tags:
      - '*'

name: release
jobs:
    release:
        name: run goreleaser
        runs-on: ubuntu-latest
        steps:
          - name: git checkout
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
            with:
              fetch-depth: 0

          - name: install go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.7'

          - name: Login to push.soh.re
            uses: docker/login-action@v3
            with:
              registry: push.soh.re
              username: ${{ secrets.SOHRE_USERNAME }}
              password: ${{ secrets.SOHRE_PASSWORD }}


          - name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v5
            with:
              version: latest
              args: release --rm-dist
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
